server:
  tomcat:
    threads:
      max: 1
  port: 9080
  host: 0.0.0.0
dict:
  store:
    small:
      checkoutLines: 2
      workingCheckoutLines: 1
      rackCellPerVisibility: 3
    medium:
      checkoutLines: 8
      workingCheckoutLines: 5
      rackCellPerVisibility: 5
    large:
      checkoutLines: 16
      workingCheckoutLines: 11
      rackCellPerVisibility: 9
  employee:
    junior:
      experience: 10-30
      salary: 150
    middle:
      experience: 30-70
      salary: 270
    senior:
      experience: 70-100
      salary: 420
  stock:
    -  name: Картофель
       price: 52
    -  name: Морковь
       price: 41
    -  name: Лук
       price: 10
    -  name: Чеснок
       price: 16
    -  name: Петрушка
       price: 26
    -  name: Укроп
       price: 25
    -  name: Лимон
       price: 20
    -  name: Масло сливочное
       price: 110
    -  name: Кефир
       price: 62
    -  name: Молоко
       price: 55
    -  name: Сметана
       price: 45
    -  name: Творог
       price: 64
    -  name: Сыр
       price: 141
    -  name: Горчица
       price: 32
    -  name: Малиновое варенье
       price: 51
    -  name: Томатная паста
       price: 42
    -  name: Тунец консервированный
       price: 120
    -  name: Молоко сгущеное
       price: 100
    -  name: Мед
       price: 90
    -  name: Яйцо куриное (десяток)
       price: 60
    -  name: Куриное филе
       price: 187
    -  name: Свинина филе
       price: 193
    -  name: Говядина лопатка
       price: 231
    -  name: Палтус мороженый
       price: 195
    -  name: Маргарин
       price: 67
    -  name: Крабовые палочки
       price: 113
    -  name: Майонез
       price: 122
    -  name: Мука пшеничная
       price: 74
    -  name: Сахар коричневый
       price: 111
    -  name: Желатин
       price: 79
    -  name: Горький шоколад
       price: 243
    -  name: Масло оливковое
       price: 233
    -  name: Гречка 1кг
       price: 43
    -  name: Перловка 1кг
       price: 46
    -  name: Рис 1кг
       price: 57
    -  name: Панировачные сухари
       price: 60
    -  name: Черный перец
       price: 12
    -  name: Лавровый лист
       price: 15
    -  name: Чай 300г
       price: 176
    -  name: Кофе 300г
       price: 303
    -  name: Какао порошок 100г
       price: 290
    -  name: Мешки для мусора
       price: 110
    -  name: Фольга
       price: 96
    -  name: Пищевая пленка
       price: 92
    -  name: Бумага для выпечки
       price: 87
    -  name: Губки для мытья посуды
       price: 23
  firstNames:
    - Алла
    - Ирина
    - Жанна
    - Полина
    - Анастасия
    - Анна
    - Светлана
    - София
    - Валентина
    - Вера
    - Надежда
    - Людмила
    - Екатерина
    - Марина
    - Мария
    - Мирослава
    - Дарья
    - Евгения
    - Нина
    - Наталья
    - Елена
    - Елизавета
  lastNames:
    - Морозова
    - Соколова
    - Щукина
    - Капустина
    - Осипова
    - Лапина
    - Рыбакова
    - Зайцева
    - Голубева
    - Осипова
    - Терешкова
    - Гусева
spring:
  banner:
    location: banner.txt